### ISSUE TITLE
Terraform Apply not working on apply

### ISSUE THREAD

**Issue by jamesgreen-moj** [ministryofjustice/mojo-aws-github-oidc-provider#17]
GitHub actions was previously applying Terrform changes, but now the GitHub actions fails on INIT. This will need to be investigated.

**Comment by smjmoj** [comment]
Related to the architecture used for the provider hash.
see:
https://stackoverflow.com/questions/67204811/terraform-failed-to-install-provider-doesnt-match-checksums-from-dependency-l

This looks like the solution https://stackoverflow.com/a/67204812

**Comment by smjmoj** [comment]
During the investigation of this issue I realised the static-code-analysis GitHub Action was failing. This wasn't due to an issue with the terraform code but a bug introduced into the GitHub Action recently.
Brought it to the attention of the Ops Engineering team; we worked through fixing that.
Fix issue:
https://github.com/ministryofjustice/github-actions/commit/7f375cc38f228b50e93c2072ef34d79210692080
Fix typo in the variable name:
https://github.com/ministryofjustice/github-actions/commit/5b6bc4c2de0315c71146c43ac64946ab12ea475b

Waiting for a new release on that repo from v15 to v15
